apiVersion: v1
kind: Service

metadata:
  name: budgetpro
  namespace: budgetpro

spec:
  type: NodePort

  selector:
    app: budgetpro

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080